import os
import sipconfig
from PyQt5 import QtCore

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "ilwisobjects.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
os.system(" ".join([config.sip_bin, "-c", ".", "-b", build_file, "-I C:/Python33/Lib/site-packages/PyQt5/sip/PyQt5/",QtCore.PYQT_CONFIGURATION['sip_flags'], "ilwisobjects.sip"]))

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_include_dirs = ["C:/Users/Poku/dev/Ilwis4/projects/IlwisCore/core",
"C:/Qt/Qt5.1.1/5.1.1/mingw48_32/include/QtCore",
"C:/Qt/Qt5.1.1/5.1.1/mingw48_32/include",
"C:/Python33/Lib/site-packages/PyQt5/include",
"C:/Users/Poku/dev/Ilwis4/projects/IlwisCore/core/util",
"C:/Users/Poku/dev/Ilwis4/projects/IlwisCore/core/catalog"
]
makefile.extra_lflags = ["ilwisobject.o","-LC:/Users/Poku/dev/Ilwis4/projects/libraries/win32debug/core"]
makefile.extra_libs = ["ilwiscore"]
makefile.extra_cxxflags = ["-std=c++11"]
# Generate the Makefile itself.
makefile.generate()
