/* 
Copyright (C) 2007 - 2015 52°North Initiative for Geospatial Open Source
Software GmbH

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

If the program is linked with libraries which are licensed under one of
the following licenses, the combination of the program with the linked
library is not considered a "derivative work" of the program:

      • Apache License, version 2.0
      • Apache Software License, version 1.0
      • GNU Lesser General Public License, version 3
      • Mozilla Public License, versions 1.0, 1.1 and 2.0
      • Common Development and Distribution License (CDDL), version 1.0

Therefore the distribution of the program linked with libraries licensed
under the aforementioned licenses, is permitted by the copyright holders
if the distribution is compliant with both the GNU General Public
License version 2 and the aforementioned licenses.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details. 
*/ 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.n52.ilwis.java;

public class ColorPalette extends ItemRange {
  private long swigCPtr;

  protected ColorPalette(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.ColorPalette_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ColorPalette obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_ColorPalette(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ColorPalette() {
    this(ilwisobjectsJNI.new_ColorPalette(), true);
  }

  public Color item(long raw) {
    return new Color(ilwisobjectsJNI.ColorPalette_item__SWIG_0(swigCPtr, this, raw), true);
  }

  public Color item(String name) {
    return new Color(ilwisobjectsJNI.ColorPalette_item__SWIG_1(swigCPtr, this, name), true);
  }

  public Color itemByOrder(long index) {
    return new Color(ilwisobjectsJNI.ColorPalette_itemByOrder(swigCPtr, this, index), true);
  }

  public Color color(int index) {
    return new Color(ilwisobjectsJNI.ColorPalette_color(swigCPtr, this, index), true);
  }

  public void add(Color pyColor) {
    ilwisobjectsJNI.ColorPalette_add(swigCPtr, this, Color.getCPtr(pyColor), pyColor);
  }

  public void remove(String name) {
    ilwisobjectsJNI.ColorPalette_remove(swigCPtr, this, name);
  }

  public void clear() {
    ilwisobjectsJNI.ColorPalette_clear(swigCPtr, this);
  }

  public boolean containsColor(Color clr, boolean inclusive) {
    return ilwisobjectsJNI.ColorPalette_containsColor__SWIG_0(swigCPtr, this, Color.getCPtr(clr), clr, inclusive);
  }

  public boolean containsColor(Color clr) {
    return ilwisobjectsJNI.ColorPalette_containsColor__SWIG_1(swigCPtr, this, Color.getCPtr(clr), clr);
  }

  public boolean containsRange(ColorRange v, boolean inclusive) {
    return ilwisobjectsJNI.ColorPalette_containsRange__SWIG_0(swigCPtr, this, ColorRange.getCPtr(v), v, inclusive);
  }

  public boolean containsRange(ColorRange v) {
    return ilwisobjectsJNI.ColorPalette_containsRange__SWIG_1(swigCPtr, this, ColorRange.getCPtr(v), v);
  }

  public long count() {
    return ilwisobjectsJNI.ColorPalette_count(swigCPtr, this);
  }

  public Color valueAt(long index, ItemRange rng) {
    return new Color(ilwisobjectsJNI.ColorPalette_valueAt(swigCPtr, this, index, ItemRange.getCPtr(rng), rng), true);
  }

  public int gotoIndex(int index, int step) {
    return ilwisobjectsJNI.ColorPalette_gotoIndex(swigCPtr, this, index, step);
  }

}
