/* 
Copyright (C) 2007 - 2015 52°North Initiative for Geospatial Open Source
Software GmbH

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

If the program is linked with libraries which are licensed under one of
the following licenses, the combination of the program with the linked
library is not considered a "derivative work" of the program:

      • Apache License, version 2.0
      • Apache Software License, version 1.0
      • GNU Lesser General Public License, version 3
      • Mozilla Public License, versions 1.0, 1.1 and 2.0
      • Common Development and Distribution License (CDDL), version 1.0

Therefore the distribution of the program linked with libraries licensed
under the aforementioned licenses, is permitted by the copyright holders
if the distribution is compliant with both the GNU General Public
License version 2 and the aforementioned licenses.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details. 
*/ 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.n52.ilwis.java;
import java.util.Iterator;
public class FeatureIterator implements Iterator<Feature> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FeatureIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FeatureIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_FeatureIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }
    public void remove() { } // Filler function
  public FeatureIterator(FeatureCoverage fc) {
    this(ilwisobjectsJNI.new_FeatureIterator__SWIG_0(FeatureCoverage.getCPtr(fc), fc), true);
  }

  public FeatureIterator(FeatureIterator it) {
    this(ilwisobjectsJNI.new_FeatureIterator__SWIG_1(FeatureIterator.getCPtr(it), it), true);
  }

  public Feature next() {
    return new Feature(ilwisobjectsJNI.FeatureIterator_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return ilwisobjectsJNI.FeatureIterator_hasNext(swigCPtr, this);
  }

  public Feature current() {
    return new Feature(ilwisobjectsJNI.FeatureIterator_current(swigCPtr, this), true);
  }

  public FeatureIterator iterator() {
    long cPtr = ilwisobjectsJNI.FeatureIterator_iterator(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureIterator(cPtr, false);
  }

  public String toString() {
    return ilwisobjectsJNI.FeatureIterator_toString(swigCPtr, this);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.FeatureIterator_isValid(swigCPtr, this);
  }

  public boolean equals(FeatureIterator other) {
    return ilwisobjectsJNI.FeatureIterator_equals(swigCPtr, this, FeatureIterator.getCPtr(other), other);
  }

  public boolean notequal(FeatureIterator other) {
    return ilwisobjectsJNI.FeatureIterator_notequal(swigCPtr, this, FeatureIterator.getCPtr(other), other);
  }

  public FeatureIterator add(int n) {
    return new FeatureIterator(ilwisobjectsJNI.FeatureIterator_add(swigCPtr, this, n), true);
  }

  public FeatureIterator __radd__(int n) {
    return new FeatureIterator(ilwisobjectsJNI.FeatureIterator___radd__(swigCPtr, this, n), true);
  }

  public FeatureIterator subtract(int n) {
    return new FeatureIterator(ilwisobjectsJNI.FeatureIterator_subtract(swigCPtr, this, n), true);
  }

}
