/* 
Copyright (C) 2007 - 2015 52°North Initiative for Geospatial Open Source
Software GmbH

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

If the program is linked with libraries which are licensed under one of
the following licenses, the combination of the program with the linked
library is not considered a "derivative work" of the program:

      • Apache License, version 2.0
      • Apache Software License, version 1.0
      • GNU Lesser General Public License, version 3
      • Mozilla Public License, versions 1.0, 1.1 and 2.0
      • Common Development and Distribution License (CDDL), version 1.0

Therefore the distribution of the program linked with libraries licensed
under the aforementioned licenses, is permitted by the copyright holders
if the distribution is compliant with both the GNU General Public
License version 2 and the aforementioned licenses.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details. 
*/ 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.n52.ilwis.java;

public class IlwisOperation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IlwisOperation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IlwisOperation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_IlwisOperation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IlwisOperation() {
    this(ilwisobjectsJNI.new_IlwisOperation__SWIG_0(), true);
  }

  public IlwisOperation(SWIGTYPE_p_Ilwis__Resource res) {
    this(ilwisobjectsJNI.new_IlwisOperation__SWIG_1(SWIGTYPE_p_Ilwis__Resource.getCPtr(res)), true);
  }

  public IlwisOperation(IlwisOperation other) {
    this(ilwisobjectsJNI.new_IlwisOperation__SWIG_2(IlwisOperation.getCPtr(other), other), true);
  }

  public String getName() {
    return ilwisobjectsJNI.IlwisOperation_getName(swigCPtr, this);
  }

  public String getSyntax() {
    return ilwisobjectsJNI.IlwisOperation_getSyntax(swigCPtr, this);
  }

  public String getLongname() {
    return ilwisobjectsJNI.IlwisOperation_getLongname(swigCPtr, this);
  }

  public String getKeyword() {
    return ilwisobjectsJNI.IlwisOperation_getKeyword(swigCPtr, this);
  }

  public String getInparameters() {
    return ilwisobjectsJNI.IlwisOperation_getInparameters(swigCPtr, this);
  }

  public String getOutparameters() {
    return ilwisobjectsJNI.IlwisOperation_getOutparameters(swigCPtr, this);
  }

  public long getId() {
    return ilwisobjectsJNI.IlwisOperation_getId(swigCPtr, this);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.IlwisOperation_isValid(swigCPtr, this);
  }

  public String getPinName(int orderNumber) {
    return ilwisobjectsJNI.IlwisOperation_getPinName(swigCPtr, this, orderNumber);
  }

  public long getPinType(int orderNumber) {
    return ilwisobjectsJNI.IlwisOperation_getPinType(swigCPtr, this, orderNumber);
  }

  public String getPinDesc(int orderNumber) {
    return ilwisobjectsJNI.IlwisOperation_getPinDesc(swigCPtr, this, orderNumber);
  }

  public String getPoutName(int orderNumber) {
    return ilwisobjectsJNI.IlwisOperation_getPoutName(swigCPtr, this, orderNumber);
  }

  public long getPoutType(int orderNumber) {
    return ilwisobjectsJNI.IlwisOperation_getPoutType(swigCPtr, this, orderNumber);
  }

  public String getPoutDesc(int orderNumber) {
    return ilwisobjectsJNI.IlwisOperation_getPoutDesc(swigCPtr, this, orderNumber);
  }

}
