/* 
Copyright (C) 2007 - 2015 52°North Initiative for Geospatial Open Source
Software GmbH

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

If the program is linked with libraries which are licensed under one of
the following licenses, the combination of the program with the linked
library is not considered a "derivative work" of the program:

      • Apache License, version 2.0
      • Apache Software License, version 1.0
      • GNU Lesser General Public License, version 3
      • Mozilla Public License, versions 1.0, 1.1 and 2.0
      • Common Development and Distribution License (CDDL), version 1.0

Therefore the distribution of the program linked with libraries licensed
under the aforementioned licenses, is permitted by the copyright holders
if the distribution is compliant with both the GNU General Public
License version 2 and the aforementioned licenses.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details. 
*/ 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.n52.ilwis.java;

public class IndexedIdentifier extends DomainItem {
  private long swigCPtr;

  protected IndexedIdentifier(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.IndexedIdentifier_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexedIdentifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_IndexedIdentifier(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IndexedIdentifier() {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_0(), true);
  }

  public IndexedIdentifier(String label, long ind, int cnt) {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_1(label, ind, cnt), true);
  }

  public IndexedIdentifier(String label, long ind) {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_2(label, ind), true);
  }

  public IndexedIdentifier(String label) {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_3(label), true);
  }

  public IndexedIdentifier(SWIGTYPE_p_Ilwis__DomainItem ilwItem) {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_4(SWIGTYPE_p_Ilwis__DomainItem.getCPtr(ilwItem)), true);
  }

  public String prefix() {
    return ilwisobjectsJNI.IndexedIdentifier_prefix(swigCPtr, this);
  }

  public void setPrefix(String name) {
    ilwisobjectsJNI.IndexedIdentifier_setPrefix(swigCPtr, this, name);
  }

  public boolean equals(IndexedIdentifier item) {
    return ilwisobjectsJNI.IndexedIdentifier_equals(swigCPtr, this, IndexedIdentifier.getCPtr(item), item);
  }

}
