/* 
Copyright (C) 2007 - 2015 52°North Initiative for Geospatial Open Source
Software GmbH

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

If the program is linked with libraries which are licensed under one of
the following licenses, the combination of the program with the linked
library is not considered a "derivative work" of the program:

      • Apache License, version 2.0
      • Apache Software License, version 1.0
      • GNU Lesser General Public License, version 3
      • Mozilla Public License, versions 1.0, 1.1 and 2.0
      • Common Development and Distribution License (CDDL), version 1.0

Therefore the distribution of the program linked with libraries licensed
under the aforementioned licenses, is permitted by the copyright holders
if the distribution is compliant with both the GNU General Public
License version 2 and the aforementioned licenses.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details. 
*/ 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.n52.ilwis.java;

public class NumericRange extends Range implements Iterable<Double> {
  private long swigCPtr;

  protected NumericRange(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.NumericRange_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NumericRange obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_NumericRange(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NumericRange(double mi, double ma, double resolution) {
    this(ilwisobjectsJNI.new_NumericRange__SWIG_0(mi, ma, resolution), true);
  }

  public NumericRange(double mi, double ma) {
    this(ilwisobjectsJNI.new_NumericRange__SWIG_1(mi, ma), true);
  }

  public NumericRange(NumericRange vr) {
    this(ilwisobjectsJNI.new_NumericRange__SWIG_2(NumericRange.getCPtr(vr), vr), true);
  }

  public NumericRange(SWIGTYPE_p_Ilwis__NumericRange nr) {
    this(ilwisobjectsJNI.new_NumericRange__SWIG_3(SWIGTYPE_p_Ilwis__NumericRange.getCPtr(nr)), true);
  }

  public NumericRange() {
    this(ilwisobjectsJNI.new_NumericRange__SWIG_4(), true);
  }

  public boolean contains(double v, boolean inclusive) {
    return ilwisobjectsJNI.NumericRange_contains__SWIG_0(swigCPtr, this, v, inclusive);
  }

  public boolean contains(double v) {
    return ilwisobjectsJNI.NumericRange_contains__SWIG_1(swigCPtr, this, v);
  }

  public double max() {
    return ilwisobjectsJNI.NumericRange_max(swigCPtr, this);
  }

  public void setMax(double v) {
    ilwisobjectsJNI.NumericRange_setMax(swigCPtr, this, v);
  }

  public double min() {
    return ilwisobjectsJNI.NumericRange_min(swigCPtr, this);
  }

  public void setMin(double v) {
    ilwisobjectsJNI.NumericRange_setMin(swigCPtr, this, v);
  }

  public double distance() {
    return ilwisobjectsJNI.NumericRange_distance(swigCPtr, this);
  }

  public void setResolution(double resolution) {
    ilwisobjectsJNI.NumericRange_setResolution(swigCPtr, this, resolution);
  }

  public double resolution() {
    return ilwisobjectsJNI.NumericRange_resolution(swigCPtr, this);
  }

  public void set(NumericRange vr) {
    ilwisobjectsJNI.NumericRange_set(swigCPtr, this, NumericRange.getCPtr(vr), vr);
  }

  public NumericRangeIterator iterator() {
    return new NumericRangeIterator(ilwisobjectsJNI.NumericRange_iterator(swigCPtr, this), true);
  }

  public NumericRangeIterator begin() {
    return new NumericRangeIterator(ilwisobjectsJNI.NumericRange_begin(swigCPtr, this), true);
  }

  public NumericRangeIterator end() {
    return new NumericRangeIterator(ilwisobjectsJNI.NumericRange_end(swigCPtr, this), true);
  }

  public void clear() {
    ilwisobjectsJNI.NumericRange_clear(swigCPtr, this);
  }

}
