/* 
Copyright (C) 2007 - 2015 52°North Initiative for Geospatial Open Source
Software GmbH

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

If the program is linked with libraries which are licensed under one of
the following licenses, the combination of the program with the linked
library is not considered a "derivative work" of the program:

      • Apache License, version 2.0
      • Apache Software License, version 1.0
      • GNU Lesser General Public License, version 3
      • Mozilla Public License, versions 1.0, 1.1 and 2.0
      • Common Development and Distribution License (CDDL), version 1.0

Therefore the distribution of the program linked with libraries licensed
under the aforementioned licenses, is permitted by the copyright holders
if the distribution is compliant with both the GNU General Public
License version 2 and the aforementioned licenses.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details. 
*/ 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.n52.ilwis.java;

public class Pixel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Pixel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pixel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_Pixel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Pixel(Pixel pixel) {
    this(ilwisobjectsJNI.new_Pixel__SWIG_0(Pixel.getCPtr(pixel), pixel), true);
  }

  public Pixel(PixelD pixel) {
    this(ilwisobjectsJNI.new_Pixel__SWIG_1(PixelD.getCPtr(pixel), pixel), true);
  }

  public Pixel(int x, int y) {
    this(ilwisobjectsJNI.new_Pixel__SWIG_2(x, y), true);
  }

  public Pixel(int x, int y, int z) {
    this(ilwisobjectsJNI.new_Pixel__SWIG_3(x, y, z), true);
  }

  public int x() {
    return ilwisobjectsJNI.Pixel_x(swigCPtr, this);
  }

  public int y() {
    return ilwisobjectsJNI.Pixel_y(swigCPtr, this);
  }

  public int z() {
    return ilwisobjectsJNI.Pixel_z(swigCPtr, this);
  }

  public void setX(int v) {
    ilwisobjectsJNI.Pixel_setX(swigCPtr, this, v);
  }

  public void setY(int v) {
    ilwisobjectsJNI.Pixel_setY(swigCPtr, this, v);
  }

  public void setZ(int v) {
    ilwisobjectsJNI.Pixel_setZ(swigCPtr, this, v);
  }

  public boolean is3D() {
    return ilwisobjectsJNI.Pixel_is3D(swigCPtr, this);
  }

  public Pixel multiply(int n) {
    long cPtr = ilwisobjectsJNI.Pixel_multiply(swigCPtr, this, n);
    return (cPtr == 0) ? null : new Pixel(cPtr, false);
  }

  public Pixel divide(int n) {
    long cPtr = ilwisobjectsJNI.Pixel_divide(swigCPtr, this, n);
    return (cPtr == 0) ? null : new Pixel(cPtr, false);
  }

  public boolean equals(Pixel other) {
    return ilwisobjectsJNI.Pixel_equals(swigCPtr, this, Pixel.getCPtr(other), other);
  }

  public boolean notequal(Pixel other) {
    return ilwisobjectsJNI.Pixel_notequal(swigCPtr, this, Pixel.getCPtr(other), other);
  }

  public String toString() {
    return ilwisobjectsJNI.Pixel_toString(swigCPtr, this);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.Pixel_isValid(swigCPtr, this);
  }

}
