/* 
Copyright (C) 2007 - 2015 52°North Initiative for Geospatial Open Source
Software GmbH

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

If the program is linked with libraries which are licensed under one of
the following licenses, the combination of the program with the linked
library is not considered a "derivative work" of the program:

      • Apache License, version 2.0
      • Apache Software License, version 1.0
      • GNU Lesser General Public License, version 3
      • Mozilla Public License, versions 1.0, 1.1 and 2.0
      • Common Development and Distribution License (CDDL), version 1.0

Therefore the distribution of the program linked with libraries licensed
under the aforementioned licenses, is permitted by the copyright holders
if the distribution is compliant with both the GNU General Public
License version 2 and the aforementioned licenses.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details. 
*/ 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.n52.ilwis.java;

public class Table extends IlwisObject {
  private long swigCPtr;

  protected Table(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.Table_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Table obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_Table(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Table() {
    this(ilwisobjectsJNI.new_Table__SWIG_0(), true);
  }

  public Table(String resource, IOOptions opt) {
    this(ilwisobjectsJNI.new_Table__SWIG_1(resource, IOOptions.getCPtr(opt), opt), true);
  }

  public Table(String resource) {
    this(ilwisobjectsJNI.new_Table__SWIG_2(resource), true);
  }

  public long columnCount() {
    return ilwisobjectsJNI.Table_columnCount(swigCPtr, this);
  }

  public vectors columns() {
    return new vectors(ilwisobjectsJNI.Table_columns(swigCPtr, this), true);
  }

  public boolean addColumn(String name, String domain) {
    return ilwisobjectsJNI.Table_addColumn__SWIG_0(swigCPtr, this, name, domain);
  }

  public boolean addColumn(ColumnDefinition coldef) {
    return ilwisobjectsJNI.Table_addColumn__SWIG_1(swigCPtr, this, ColumnDefinition.getCPtr(coldef), coldef);
  }

  public int columnIndex(String name) {
    return ilwisobjectsJNI.Table_columnIndex(swigCPtr, this, name);
  }

  public vectors column(String name) {
    return new vectors(ilwisobjectsJNI.Table_column__SWIG_0(swigCPtr, this, name), true);
  }

  public vectors column(long columnIndex) {
    return new vectors(ilwisobjectsJNI.Table_column__SWIG_1(swigCPtr, this, columnIndex), true);
  }

  public long recordCount() {
    return ilwisobjectsJNI.Table_recordCount(swigCPtr, this);
  }

  public vectorl select(String conditions) {
    return new vectorl(ilwisobjectsJNI.Table_select(swigCPtr, this, conditions), true);
  }

  public vectors record(long rec) {
    return new vectors(ilwisobjectsJNI.Table_record(swigCPtr, this, rec), true);
  }

  public String cell(String name, long rec) {
    return ilwisobjectsJNI.Table_cell__SWIG_0(swigCPtr, this, name, rec);
  }

  public String cell(long colIndex, long rec) {
    return ilwisobjectsJNI.Table_cell__SWIG_1(swigCPtr, this, colIndex, rec);
  }

  public void setCell(String name, long rec, SWIGTYPE_p_QVariant value) {
    ilwisobjectsJNI.Table_setCell__SWIG_0(swigCPtr, this, name, rec, SWIGTYPE_p_QVariant.getCPtr(value));
  }

  public void setCell(long colIndex, long rec, SWIGTYPE_p_QVariant value) {
    ilwisobjectsJNI.Table_setCell__SWIG_1(swigCPtr, this, colIndex, rec, SWIGTYPE_p_QVariant.getCPtr(value));
  }

  public void setCell(String name, long rec, long value) {
    ilwisobjectsJNI.Table_setCell__SWIG_2(swigCPtr, this, name, rec, value);
  }

  public void setCell(long colIndex, long rec, long value) {
    ilwisobjectsJNI.Table_setCell__SWIG_3(swigCPtr, this, colIndex, rec, value);
  }

  public void setCell(String name, long rec, String value) {
    ilwisobjectsJNI.Table_setCell__SWIG_4(swigCPtr, this, name, rec, value);
  }

  public void setCell(long colIndex, long rec, String value) {
    ilwisobjectsJNI.Table_setCell__SWIG_5(swigCPtr, this, colIndex, rec, value);
  }

  public void setCell(String name, long rec, double value) {
    ilwisobjectsJNI.Table_setCell__SWIG_6(swigCPtr, this, name, rec, value);
  }

  public void setCell(long colIndex, long rec, double value) {
    ilwisobjectsJNI.Table_setCell__SWIG_7(swigCPtr, this, colIndex, rec, value);
  }

  public static Table toTable(IObject obj) {
    long cPtr = ilwisobjectsJNI.Table_toTable(IObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new Table(cPtr, false);
  }

  public ColumnDefinition columnDefinition(String name) {
    return new ColumnDefinition(ilwisobjectsJNI.Table_columnDefinition__SWIG_0(swigCPtr, this, name), true);
  }

  public ColumnDefinition columnDefinition(long index) {
    return new ColumnDefinition(ilwisobjectsJNI.Table_columnDefinition__SWIG_1(swigCPtr, this, index), true);
  }

  public void setColumnDefinition(ColumnDefinition coldef) {
    ilwisobjectsJNI.Table_setColumnDefinition__SWIG_0(swigCPtr, this, ColumnDefinition.getCPtr(coldef), coldef);
  }

  public void setColumnDefinition(String name, ColumnDefinition coldef) {
    ilwisobjectsJNI.Table_setColumnDefinition__SWIG_1(swigCPtr, this, name, ColumnDefinition.getCPtr(coldef), coldef);
  }

  public void setColumnDefinition(long index, ColumnDefinition coldef) {
    ilwisobjectsJNI.Table_setColumnDefinition__SWIG_2(swigCPtr, this, index, ColumnDefinition.getCPtr(coldef), coldef);
  }

}
