/* 
Copyright (C) 2007 - 2015 52°North Initiative for Geospatial Open Source
Software GmbH

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

If the program is linked with libraries which are licensed under one of
the following licenses, the combination of the program with the linked
library is not considered a "derivative work" of the program:

      • Apache License, version 2.0
      • Apache Software License, version 1.0
      • GNU Lesser General Public License, version 3
      • Mozilla Public License, versions 1.0, 1.1 and 2.0
      • Common Development and Distribution License (CDDL), version 1.0

Therefore the distribution of the program linked with libraries licensed
under the aforementioned licenses, is permitted by the copyright holders
if the distribution is compliant with both the GNU General Public
License version 2 and the aforementioned licenses.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details. 
*/ 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.n52.ilwis.java;
import java.util.Iterator;
public class VertexIterator implements Iterator<Coordinate> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VertexIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VertexIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_VertexIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }
    public void remove() { } // Filler function
  public VertexIterator() {
    this(ilwisobjectsJNI.new_VertexIterator__SWIG_0(), true);
  }

  public VertexIterator(Geometry geom) {
    this(ilwisobjectsJNI.new_VertexIterator__SWIG_1(Geometry.getCPtr(geom), geom), true);
  }

  public VertexIterator(String wkt) {
    this(ilwisobjectsJNI.new_VertexIterator__SWIG_2(wkt), true);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.VertexIterator_isValid(swigCPtr, this);
  }

  public String toString() {
    return ilwisobjectsJNI.VertexIterator_toString(swigCPtr, this);
  }

  public VertexIterator iterator() {
    long cPtr = ilwisobjectsJNI.VertexIterator_iterator(swigCPtr, this);
    return (cPtr == 0) ? null : new VertexIterator(cPtr, false);
  }

  public Coordinate next() {
    return new Coordinate(ilwisobjectsJNI.VertexIterator_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return ilwisobjectsJNI.VertexIterator_hasNext(swigCPtr, this);
  }

  public VertexIterator add(int n) {
    return new VertexIterator(ilwisobjectsJNI.VertexIterator_add(swigCPtr, this, n), true);
  }

  public VertexIterator __radd__(int n) {
    return new VertexIterator(ilwisobjectsJNI.VertexIterator___radd__(swigCPtr, this, n), true);
  }

  public VertexIterator increase(int n) {
    long cPtr = ilwisobjectsJNI.VertexIterator_increase(swigCPtr, this, n);
    return (cPtr == 0) ? null : new VertexIterator(cPtr, false);
  }

  public VertexIterator subtract(int n) {
    return new VertexIterator(ilwisobjectsJNI.VertexIterator_subtract(swigCPtr, this, n), true);
  }

  public VertexIterator __rsub__(int n) {
    return new VertexIterator(ilwisobjectsJNI.VertexIterator___rsub__(swigCPtr, this, n), true);
  }

  public VertexIterator decrease(int n) {
    long cPtr = ilwisobjectsJNI.VertexIterator_decrease(swigCPtr, this, n);
    return (cPtr == 0) ? null : new VertexIterator(cPtr, false);
  }

  public Coordinate get(long linearpos) {
    return new Coordinate(ilwisobjectsJNI.VertexIterator_get(swigCPtr, this, linearpos), true);
  }

  public Coordinate current() {
    return new Coordinate(ilwisobjectsJNI.VertexIterator_current(swigCPtr, this), true);
  }

  public int compareTo(VertexIterator other) {
    return ilwisobjectsJNI.VertexIterator_compareTo(swigCPtr, this, VertexIterator.getCPtr(other), other);
  }

  public boolean nextSubGeometry() {
    return ilwisobjectsJNI.VertexIterator_nextSubGeometry(swigCPtr, this);
  }

  public boolean isInteriorVertex() {
    return ilwisobjectsJNI.VertexIterator_isInteriorVertex(swigCPtr, this);
  }

  public VertexIterator begin() {
    return new VertexIterator(ilwisobjectsJNI.VertexIterator_begin(swigCPtr, this), true);
  }

  public VertexIterator end() {
    return new VertexIterator(ilwisobjectsJNI.VertexIterator_end(swigCPtr, this), true);
  }

}
